#!/bin/bash

./script/build_venv.sh
source .venv/bin/activate
sudo systemctl start mongod.service
# Start process 1 in the background
cd backend/
python3 app.py &
process1_pid=$!

# Start process 2 in the background
cd ../frontend/
npm start &
process2_pid=$!

echo "Processes started with PIDs: $process1_pid, $process2_pid"

# Function to stop the processes
stop_processes() {
    echo "Stopping processes..."

    # Send SIGTERM signal to process 1
    kill $process1_pid

    # Send SIGTERM signal to process 2
    kill $process2_pid

    echo "Processes stopped."
}

# Trap the SIGINT signal (Ctrl+C) to call stop_processes function
trap 'stop_processes' SIGINT

# Wait for the processes to finish
wait
