services:

  frontend: 
    build: ./frontend
    depends_on:
      - nginx
    ports:
      - "3000:3000"
    networks:
      - mynetwork

  mongo:
    image: mongo:4.2.5  
    volumes:
      # Mount the init folder containing the data and script
      - ./mongo/init:/docker-entrypoint-initdb.d
    environment:
      MONGO_INITDB_DATABASE: ProductDb
    ports:
      - "27017:27017"

    networks:
      - mynetwork
  
  nginx:
    build: ./nginx
    depends_on:
      - backend
    environment:
      - WEB_CERT=/app/.s/cert.pem
      - WEB_KEY=/app/.s/key.pem
    ports:
      - "3001:3001"
    networks:
      - mynetwork
    volumes:
      - ~/.ssl:/app/.s
  
  client_com:
    build: ./OrderManager
    ports:
      - "3002:3002"
    networks:
      - mynetwork

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - ENV=docker
      - MONGO_HOST=mongo
    networks:
      - mynetwork
    depends_on:
      - mongo
networks:
  mynetwork:
    driver: bridge