services:

  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - MONGO_HOST=mongo
    networks:
      - mynetwork

  frontend: 
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:3000"
    networks:
      - mynetwork

  mongo:
    image: mongo:4.2.5  
    ports:
      - "27017:27017"
    networks:
      - mynetwork
  
  nginx:
    build: ./nginx
    ports:
      - "3001:3001"
    networks:
      - mynetwork


networks:
  mynetwork:
    driver: bridge