/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "../CategoryGrid/CategoryGrid.module.css";
import CategoryItem from "../CategoryGrid/CategoryItem";

const categories = [
  { id: 1, name: "Category 1" },
  { id: 2, name: "Category 2" },
  { id: 3, name: "Category 3" },
  { id: 4, name: "Category 4" },
  { id: 5, name: "Category 5" },
  { id: 6, name: "Category 6" },
];

const categories1 = [
  [ 
    { id: 1, name: "Stores 1" },
    { id: 2, name: "Stores 2" },
    { id: 3, name: "Stores 3" },
  ],
  [
    { id: 4, name: "Stores 4" },
    { id: 5, name: "Stores 5" },
    { id: 6, name: "Stores 6" },
  ],
  [
    { id: 4, name: "Stores 4" },
    { id: 5, name: "Stores 5" },
  ]
]
function StoresGrid() {
  return (
    <main className={styles.container}>
      <section className={styles.content}>
        <div className={styles.gridContainer}>


          {categories1.map((row) => (

            <div className={styles.grid}>
              {row.map((category) => (
                <CategoryItem key={category.id} 
                              link ='/example' 
                              name={category.name}  
                              imgLink='https://cdn.builder.io/api/v1/image/assets%2F6a53bff92dc24a62b49604417a4ec7f2%2F6032d2b5327e4c0687019aafbe79d0c2'
                              isStore={true}/>
              ))}
            </div>
          
          ))}

        </div>
      </section>
    </main>
  );
}

export default StoresGrid;
