/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./SubTitle.module.css";

export default function SubTitle({title}) {
  // const title = title1
  // const title = 'store'
  // title = title.toString()
  return (
    <main className={styles.container}>
      <section className={styles.content}>
        <h1 className={styles.title}> {title} </h1>
      </section>
    </main>
  );
}

