spring.application.name=ebazzar
server.port=5000
spring.mvc.static-path-pattern=/media/static_content/**
spring.web.resources.static-locations=file:static_content
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=ProductDb