/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styles from "./CategoryGrid.module.css";

function CategoryItem({ name, link, imgLink, isStore }) {

  // const imgUrlCall = 'url(' + imgLink + '})'
  const imgUrlCall = createImgCallFromLink(imgLink)

  return (
    <div className={styles.gridItem} >
      <a href={link} 
          style={{backgroundImage: imgUrlCall}} 
          className={styles.categoryLink} >
        
        {isStore ? 
          (<></>):
          (<span className={styles.categoryText}>{(name)}</span>)
        }
        <span className={styles["visually-hidden"]}>Go to {name}</span>
      </a>
    </div>
  );
}

const createImgCallFromLink = (str) => {
  const imgUrlCall = 'url(' + str + ')'
  return imgUrlCall
}
export default CategoryItem;
