const ORDER_TRACKING_STATUS = {
    "ORDER_NOT_FOUND": -1,
    "COURRIER_NOT_ASSIGNED": 0,
    "AWAITING_PICKUP": 1,
    "IN_TRANSIT": 2,
    "ARRIVED_AT_DESTINATION": 3,
    "DELIVERED": 4
}
export default ORDER_TRACKING_STATUS;