# Use the official Golang image as the base image
FROM golang:1.23-alpine

# Set the Current Working Directory inside the container
WORKDIR /app

# Copy go.mod and go.sum files
COPY go.mod go.sum ./

# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

ENV FRONTEND_ORIGIN=http://localhost:3000

# Copy the source code into the container
COPY . .

# Build the Go app
RUN go build -o server ./server.go


# Command to run the executable
CMD ["./server"]