#!/bin/bash

# MongoDB server connection information
MONGO_HOST=localhost
MONGO_PORT=27017
DATABASE_NAME=ProductDb

# Connect to the MongoDB server and clear the database
echo "Connecting to MongoDB server..."
mongosh $MONGO_HOST:$MONGO_PORT/$DATABASE_NAME --eval "db.dropDatabase()"
echo "Database $DATABASE_NAME has been cleared."