#!/bin/bash

if [ "$#" -ne 2 ]; then
    echo "Usage: $0 <database_name> <collection_name>"
    exit 1
fi

# Database name and collection name from arguments
DB_NAME=$1
COLLECTION_NAME=$2
MONGO_HOST=localhost
MONGO_PORT=27017

mongosh $MONGO_HOST:$MONGO_PORT/$DATABASE_NAME --eval "db.getSiblingDB('$DB_NAME').$COLLECTION_NAME.remove({})"
